In [7]:
import pandas as pd
import numpy as np


np.random.seed(42)
def createdata():
  data = {
      'Age':np.random.randint(18,70,size=20),
      'Salary':np.random.randit(3000,12000,size=20),
      'Purchased':np.random.choice([0,1],size=20),
      'Gender':np.random.choice(['Male','Female'],size=20),
      'City':np.random.choice(['Delhi','Mumbai','Banglore'],size=20)
  }

  df = pd.DataFrame(data)
  return df

  df = createdata()
  df.head(10)
  }

SyntaxError: unmatched '}' (<ipython-input-7-d3e660d86f15>, line 20)

In [8]:
# prompt: import pandas as pd
# import numpy as np
# np.random.seed(42)
# def createdata():
#   data = {
#       'Age':np.random.randint(18,70,size=20),
#       'Salary':np.random.randit(3000,12000,size=20),
#       'Purchased':np.random.choice([0,1],size=20),
#       'Gender':np.random.choice(['Male','Female'],size=20),
#       'City':np.random.choice(['Delhi','Mumbai','Banglore'],size=20)
#   }
#   df = pd.DataFrame(data)
#   return df
#   df = createdata()
#   df.head(10)
#   }

import pandas as pd
import numpy as np

np.random.seed(42)

def createdata():
    data = {
        'Age': np.random.randint(18, 70, size=20),
        'Salary': np.random.randint(3000, 12000, size=20), # Corrected: randint
        'Purchased': np.random.choice([0, 1], size=20),
        'Gender': np.random.choice(['Male', 'Female'], size=20),
        'City': np.random.choice(['Delhi', 'Mumbai', 'Banglore'], size=20)
    }
    df = pd.DataFrame(data)
    return df

df = createdata()
print(df.head(10))

   Age  Salary  Purchased  Gender      City
0   56    9949          1  Female    Mumbai
1   69    5433          1  Female    Mumbai
2   46    8311          0  Female    Mumbai
3   32    8051          0    Male     Delhi
4   60    9420          0  Female  Banglore
5   25    4184          0    Male    Mumbai
6   38    7555          0  Female    Mumbai
7   56    6385          0    Male    Mumbai
8   36    9396          0  Female    Mumbai
9   40   11666          0    Male    Mumbai

In [9]:
df.shape

(20, 5)

when u have missing value in data

In [10]:
df.loc[5,'Age'] = np.nan
df.loc[9,'Salary'] = np.nan
df.head(10)

    Age  Salary  Purchased  Gender      City
0  56.0  9949.0          1  Female    Mumbai
1  69.0  5433.0          1  Female    Mumbai
2  46.0  8311.0          0  Female    Mumbai
3  32.0  8051.0          0    Male     Delhi
4  60.0  9420.0          0  Female  Banglore
5   NaN  4184.0          0    Male    Mumbai
6  38.0  7555.0          0  Female    Mumbai
7  56.0  6385.0          0    Male    Mumbai
8  36.0  9396.0          0  Female    Mumbai
9  40.0     NaN          0    Male    Mumbai

In [12]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Salary'].fillna(df['Salary'].median(),inplace=True)
df.head(10)

<ipython-input-12-4104f26fbd1a>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].median(),inplace=True)

         Age  Salary  Purchased  Gender      City
0  56.000000  9949.0          1  Female    Mumbai
1  69.000000  5433.0          1  Female    Mumbai
2  46.000000  8311.0          0  Female    Mumbai
3  32.000000  8051.0          0    Male     Delhi
4  60.000000  9420.0          0  Female  Banglore
5  42.105263  4184.0          0    Male    Mumbai
6  38.000000  7555.0          0  Female    Mumbai
7  56.000000  6385.0          0    Male    Mumbai
8  36.000000  9396.0          0  Female    Mumbai
9  40.000000  6385.0          0    Male    Mumbai

In [13]:
df_dropped = df.dropna()
df_dropped.head(10)

         Age  Salary  Purchased  Gender      City
0  56.000000  9949.0          1  Female    Mumbai
1  69.000000  5433.0          1  Female    Mumbai
2  46.000000  8311.0          0  Female    Mumbai
3  32.000000  8051.0          0    Male     Delhi
4  60.000000  9420.0          0  Female  Banglore
5  42.105263  4184.0          0    Male    Mumbai
6  38.000000  7555.0          0  Female    Mumbai
7  56.000000  6385.0          0    Male    Mumbai
8  36.000000  9396.0          0  Female    Mumbai
9  40.000000  6385.0          0    Male    Mumbai

In [15]:
from sklearn.impute import KNNImputer
knn_imputer = KNNImputer(n_neighbors=3)
df[['Age','Salary']] = knn_imputer.fit_transform(df[['Age','Salary']])
df.head(10)

         Age  Salary  Purchased  Gender      City
0  56.000000  9949.0          1  Female    Mumbai
1  69.000000  5433.0          1  Female    Mumbai
2  46.000000  8311.0          0  Female    Mumbai
3  32.000000  8051.0          0    Male     Delhi
4  60.000000  9420.0          0  Female  Banglore
5  42.105263  4184.0          0    Male    Mumbai
6  38.000000  7555.0          0  Female    Mumbai
7  56.000000  6385.0          0    Male    Mumbai
8  36.000000  9396.0          0  Female    Mumbai
9  40.000000  6385.0          0    Male    Mumbai

In [16]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
df.head()

    Age  Salary  Purchased  Gender      City
0  56.0  9949.0          1       0    Mumbai
1  69.0  5433.0          1       0    Mumbai
2  46.0  8311.0          0       0    Mumbai
3  32.0  8051.0          0       1     Delhi
4  60.0  9420.0          0       0  Banglore

In [17]:
df = pd.get_dummies(df,columns=['City'],drop_first=True)
df.head()

    Age  Salary  Purchased  Gender  City_Delhi  City_Mumbai
0  56.0  9949.0          1       0       False         True
1  69.0  5433.0          1       0       False         True
2  46.0  8311.0          0       0       False         True
3  32.0  8051.0          0       1        True        False
4  60.0  9420.0          0       0       False        False

In [19]:
mean_target = df.groupby('Gender')['Purchased'].mean()
df['City_encoded'] = df['City'].map(mean_target)
df.head()

KeyError: 'City'